# fly.toml app configuration file generated for asset-tracker-jsf on 2023-07-06T21:28:45+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "asset-tracker-jsf"
primary_region = "sin"

[env]
  PORT = "3003"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
